name: GEO_PROJ_PYROSM_FIX
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.3.5
  - geopandas==0.10.2
  - pygeos==0.12.0
  - cykhash==1.0.2
  - pyrosm==0.6.1
  - matplotlib==3.5.1
  - geopy==2.2.0
  - osmnx==1.1.2
  - gpxpy==1.5.0
  - movingpandas==0.8rc1
  - contextily==1.2.0
  - folium==0.12.1.post1
  - leafmap==0.7.0